<?
$PERM["video"]["*"]="R";
$PERM["brands_proizvoditeli"]["51"]="W";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["test2.php"]["*"]="D";
$PERM["test.php"]["*"]="D";
$PERM["price"]["*"]="R";
$PERM["vote"]["2"]="R";
$PERM["cat"]["35"]="W";
$PERM["upload"]["6"]="W";
$PERM["upload"]["35"]="W";
$PERM["contact"]["34"]="R";
$PERM["brands"]["34"]="R";
$PERM["webstat"]["27"]="R";
$PERM["/"]["3"]="W";
$PERM["/"]["30"]="W";
$PERM["/"]["*"]="R";
$PERM["partners-ads"]["*"]="R";
$PERM["deluxe"]["*"]="D";
?>