<?php
	//echo 312;
	if($_SERVER['REQUEST_URI'] == "/brands/general-electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/gusi-electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/kosmos/"
	|| $_SERVER['REQUEST_URI'] == "/brands/general-electric/lamps-for-the-plants-ge/"
	|| $_SERVER['REQUEST_URI'] == "/brands/general-electric/lamps-for-refrigerators-and-ovens-ge/"
	|| $_SERVER['REQUEST_URI'] == "/brands/teleco/"
	|| $_SERVER['REQUEST_URI'] == "/brands/lemz/"
	|| $_SERVER['REQUEST_URI'] == "/brands/mk-electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/rev-ritter/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eljo/"
	|| $_SERVER['REQUEST_URI'] == "/brands/tj_electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/neo-neon/"
	|| $_SERVER['REQUEST_URI'] == "/brands/ovax/"
	|| $_SERVER['REQUEST_URI'] == "/brands/hyundai-telecom/"
	|| $_SERVER['REQUEST_URI'] == "/brands/rev-ritter/roll-cable/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eljo/trend/"
	|| $_SERVER['REQUEST_URI'] == "/brands/gusi-electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/teleco/radio-controlled/"
	|| $_SERVER['REQUEST_URI'] == "/brands/hyundai-telecom/"
	|| $_SERVER['REQUEST_URI'] == "/brands/diodex/"
	|| $_SERVER['REQUEST_URI'] == "/brands/kosmos/"
	|| $_SERVER['REQUEST_URI'] == "/brands/gusi-electric/gusi-electric-catalog/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eljo/"
	|| $_SERVER['REQUEST_URI'] == "/brands/general-electric/ultraviolet-and-infrared-lamps-ge/"
	|| $_SERVER['REQUEST_URI'] == "/brands/ovax/lamps-swarovski/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eljo/quick-rot/"
	|| $_SERVER['REQUEST_URI'] == "/brands/general-electric/luminescentlamps-ge/"
	|| $_SERVER['REQUEST_URI'] == "/brands/tj-electric/tj-electric-catalog/"
	|| $_SERVER['REQUEST_URI'] == "/brands/mk-electric/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eljo/aquatrend/"
	|| $_SERVER['REQUEST_URI'] == "/brands/omron/"
	|| $_SERVER['REQUEST_URI'] == "/brands/mk-electric/edge/"
	|| $_SERVER['REQUEST_URI'] == "/brands/ekf/"
	|| $_SERVER['REQUEST_URI'] == "/brands/brumberg/"
	|| $_SERVER['REQUEST_URI'] == "/brands/beghelli/"
	|| $_SERVER['REQUEST_URI'] == "/brands/bettermann/"
	|| $_SERVER['REQUEST_URI'] == "/brands/allen-bradley/"
	|| $_SERVER['REQUEST_URI'] == "/brands/pfannenberg/"
	|| $_SERVER['REQUEST_URI'] == "/brands/control-techniques/"
	|| $_SERVER['REQUEST_URI'] == "/brands/shitelektrokomplekt/"
	|| $_SERVER['REQUEST_URI'] == "/brands/eti/"
	|| $_SERVER['REQUEST_URI'] == "/brands/t-plast/"
	|| $_SERVER['REQUEST_URI'] == "/brands/ekz/"
	|| $_SERVER['REQUEST_URI'] == "/brands/lappkabel/"
	|| $_SERVER['REQUEST_URI'] == "/brands/sevkabel/"
	|| $_SERVER['REQUEST_URI'] == "/brands/elix/"
	|| $_SERVER['REQUEST_URI'] == "/brands/jsb-systems/"
	|| $_SERVER['REQUEST_URI'] == "/brands/osram/"
	|| $_SERVER['REQUEST_URI'] == "/brands/lena-lighting/"
	)
	{
		?><p style="color: rgb(255, 0, 0); padding-top:100px; font-size:16px;">Уважаемые посетители, временно данная продукция отсутствует в ассортименте компании, однако мы можем Вам предложить достойные аналоги от таких производителей как <a href="/brands/ABB/" title="ABB" >ABB</a>, <a href="/brands/Legrand/" title="Legrand" >Legrand</a>, <a href="/brands/Schneider_Electric/" title="Schneider Electric" >Schneider Electric</a>, <a href="/brands/Merten/" title="Merten" >Merten</a>, <a href="/brands/Gira/" title="Gira" >Gira</a>, <a href="/brands/Bticino/" title="Bticino" >Bticino</a> и многие другие.</p><br>
		<p style="padding-bottom:150px;">Представленные аналоги в ассортименте компании Вы можете купить по этой ссылке - <a href="/catalog/" title="электроустановочные изделия в ассортименте компании Эlevel" ><img src="/images/Knopki/kupit.png" alt="электроустановочные изделия в компании Эlevel" title="электроустановочные изделия в компании Эlevel" align="absmiddle"  /></a></p><?
	}
?>